# Site settings
title: sramirez
name: Sebastián Ramírez
email: sramirez10r@gmail.com

permalink: /:title/
base: http://sramirez.me # the base hostname

# Social
twitter_username: s_ramirez91
github_username:  s-ramirez

# Build settings
markdown: kramdown

#Disqus
disqusid: sramirez91

#Sass configuration
sass:
  sass_dir: _sass

#Languages configuration
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: "post"
      comments: true
  -
    scope:
      path: "_posts/es"
    values:
      lang: "es"
  -
    scope:
      path: "_posts/en/pages"
    values:
      type: "pages"

  -
    scope:
      path: "_posts/es/pages"
    values:
      type: "pages"
