# Site settings
title: sramirez
name: Sebastián Ramírez
description: Web developer. Software Engineer @ TEC Costa Rica. Currently pursuing an M.Sc in Computer Science @ Wake Forest University.
email: sramirez10r@gmail.com

permalink: /:title/

base: http://sramirez.me # the base hostname & protocol for your site

# Social
twitter_username: s_ramirez91
github_username:  s-ramirez

# Build settings
markdown: kramdown

#Disqus
disqusid: sramirez91

#Sass configuration
sass:
  sass_dir: _sass

#Languages configuration
defaults:
    -
        scope:
            path: ""
        values:
            lang: en
            layout: default
    -
        scope:
            path: _posts/es
        values:
            lang: es
            layout: default
